[build-system]
# Defined by PEP 518:
requires = [
        "SQLAlchemy",
        "pydantic",
        "requests",
        "pymongo",
        "rdflib",
        "fastapi",
        "uvicorn",
        "python-multipart",
        "asyncio",
        "unqlite",
        "asyncpg",
        "aiomysql",
        "aiosqlite",
        "motor",
        "aiofiles"
    ]